import { GraphData } from './types';

// Simple network map
export const simpleGraphData: GraphData = {
  nodes: [
    { id: 'A', x: 0, y: 0 },
    { id: 'B', x: 2, y: 1 },
    { id: 'C', x: 4, y: 0 },
    { id: 'D', x: 5, y: 3 },
    { id: 'E', x: 3, y: 4 },
    { id: 'F', x: 6, y: 1 },
    { id: 'G', x: 7, y: 4 },
    { id: 'H', x: 2, y: 6 },
    { id: 'I', x: 5, y: 6 },
  ],
  edges: [
    { from: 'A', to: 'B', distance: 2, allowed_modes: ['car', 'bicycle'], one_way: false },
    { from: 'B', to: 'C', distance: 2.5, allowed_modes: ['car'], one_way: false },
    { from: 'B', to: 'E', distance: 3, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
    { from: 'C', to: 'D', distance: 3, allowed_modes: ['car', 'bicycle'], one_way: true },
    { from: 'E', to: 'D', distance: 2, allowed_modes: ['pedestrian'], one_way: false },
    { from: 'A', to: 'E', distance: 5, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'C', to: 'F', distance: 1.5, allowed_modes: ['car'], one_way: false },
    { from: 'F', to: 'G', distance: 3, allowed_modes: ['car', 'bicycle'], one_way: false },
    { from: 'E', to: 'H', distance: 2.5, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
    { from: 'H', to: 'I', distance: 2, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
    { from: 'G', to: 'I', distance: 2.5, allowed_modes: ['car', 'bicycle'], one_way: false },
    { from: 'D', to: 'G', distance: 2, allowed_modes: ['car', 'bicycle'], one_way: false },
  ],
};

// City map with realistic locations
export const cityGraphData: GraphData = {
  nodes: [
    { id: 'Downtown_Plaza', x: 3, y: 5 },
    { id: 'City_Hall', x: 5, y: 5 },
    { id: 'Central_Station', x: 7, y: 5 },
    { id: 'University', x: 2, y: 7 },
    { id: 'Hospital', x: 5, y: 7 },
    { id: 'Airport', x: 8, y: 7 },
    { id: 'Park', x: 1, y: 3 },
    { id: 'Mall', x: 4, y: 3 },
    { id: 'Stadium', x: 7, y: 3 },
    { id: 'Harbor', x: 9, y: 1 },
    { id: 'Beach', x: 6, y: 1 },
    { id: 'Museum', x: 3, y: 1 },
  ],
  edges: [
    { from: 'Downtown_Plaza', to: 'City_Hall', distance: 2, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'City_Hall', to: 'Central_Station', distance: 2, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Downtown_Plaza', to: 'University', distance: 2.5, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'City_Hall', to: 'Hospital', distance: 2, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Central_Station', to: 'Airport', distance: 2.5, allowed_modes: ['car'], one_way: false },
    { from: 'University', to: 'Hospital', distance: 3, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
    { from: 'Hospital', to: 'Airport', distance: 3, allowed_modes: ['car', 'bicycle'], one_way: false },
    { from: 'Park', to: 'Downtown_Plaza', distance: 2.5, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
    { from: 'Downtown_Plaza', to: 'Mall', distance: 2, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Mall', to: 'City_Hall', distance: 1.5, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'City_Hall', to: 'Stadium', distance: 3, allowed_modes: ['car', 'bicycle'], one_way: false },
    { from: 'Central_Station', to: 'Stadium', distance: 2, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Stadium', to: 'Airport', distance: 4, allowed_modes: ['car'], one_way: false },
    { from: 'Museum', to: 'Mall', distance: 2, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
    { from: 'Beach', to: 'Mall', distance: 2.5, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Beach', to: 'Stadium', distance: 1.5, allowed_modes: ['car', 'bicycle'], one_way: false },
    { from: 'Beach', to: 'Harbor', distance: 3, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Stadium', to: 'Harbor', distance: 3, allowed_modes: ['car'], one_way: true },
    { from: 'Park', to: 'Museum', distance: 2.5, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
    { from: 'University', to: 'Park', distance: 2, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
  ],
};

// NUST H-12 Campus map
export const nustCampusData: GraphData = {
  nodes: [
    { id: 'Main_Gate', x: 1, y: 5 },
    { id: 'SEECS', x: 3, y: 7 },
    { id: 'SADA', x: 5, y: 8 },
    { id: 'SMME', x: 7, y: 7 },
    { id: 'NBS', x: 9, y: 6 },
    { id: 'SCME', x: 3, y: 5 },
    { id: 'SNS', x: 5, y: 5 },
    { id: 'Central_Library', x: 7, y: 5 },
    { id: 'Sports_Complex', x: 9, y: 4 },
    { id: 'Student_Center', x: 5, y: 3 },
    { id: 'Cafeteria', x: 3, y: 3 },
    { id: 'Medical_Center', x: 7, y: 3 },
    { id: 'Admin_Block', x: 1, y: 3 },
    { id: 'Hostel_Boys', x: 2, y: 1 },
    { id: 'Hostel_Girls', x: 4, y: 1 },
    { id: 'Faculty_Housing', x: 6, y: 1 },
    { id: 'Mosque', x: 8, y: 1 },
    { id: 'Innovation_Center', x: 10, y: 8 },
    { id: 'Research_Labs', x: 11, y: 6 },
    { id: 'Auditorium', x: 11, y: 4 },
    { id: 'Parking_A', x: 1, y: 7 },
    { id: 'Parking_B', x: 9, y: 2 },
    { id: 'Bus_Stop', x: 0, y: 5 },
    { id: 'Ground', x: 10, y: 2 },
  ],
  edges: [
    { from: 'Bus_Stop', to: 'Main_Gate', distance: 0.5, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Main_Gate', to: 'SCME', distance: 2, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Main_Gate', to: 'Admin_Block', distance: 2.5, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Main_Gate', to: 'Parking_A', distance: 2, allowed_modes: ['car'], one_way: false },
    { from: 'Parking_A', to: 'SEECS', distance: 2.5, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'SEECS', to: 'SADA', distance: 2.5, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'SADA', to: 'SMME', distance: 2.5, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'SMME', to: 'NBS', distance: 2.5, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'SADA', to: 'Innovation_Center', distance: 5, allowed_modes: ['car', 'bicycle'], one_way: false },
    { from: 'NBS', to: 'Research_Labs', distance: 2.5, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'SCME', to: 'SNS', distance: 2, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'SNS', to: 'Central_Library', distance: 2, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Central_Library', to: 'Sports_Complex', distance: 2.5, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Sports_Complex', to: 'NBS', distance: 2.5, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Sports_Complex', to: 'Auditorium', distance: 3, allowed_modes: ['car', 'bicycle'], one_way: false },
    { from: 'Research_Labs', to: 'Auditorium', distance: 2.5, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'SEECS', to: 'SCME', distance: 2, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
    { from: 'SCME', to: 'Cafeteria', distance: 2.5, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
    { from: 'SNS', to: 'Student_Center', distance: 2, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Central_Library', to: 'Medical_Center', distance: 2.5, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Student_Center', to: 'Cafeteria', distance: 2, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
    { from: 'Student_Center', to: 'Medical_Center', distance: 2, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
    { from: 'Admin_Block', to: 'Cafeteria', distance: 2, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Medical_Center', to: 'Sports_Complex', distance: 2.5, allowed_modes: ['car', 'bicycle'], one_way: false },
    { from: 'Cafeteria', to: 'Hostel_Boys', distance: 2.5, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
    { from: 'Student_Center', to: 'Hostel_Girls', distance: 2.5, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
    { from: 'Hostel_Boys', to: 'Hostel_Girls', distance: 2, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Hostel_Girls', to: 'Faculty_Housing', distance: 2, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Faculty_Housing', to: 'Mosque', distance: 2, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Mosque', to: 'Parking_B', distance: 2, allowed_modes: ['car'], one_way: false },
    { from: 'Mosque', to: 'Ground', distance: 2.5, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
    { from: 'Parking_B', to: 'Ground', distance: 2, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'Ground', to: 'Auditorium', distance: 3, allowed_modes: ['car', 'bicycle'], one_way: false },
    { from: 'Medical_Center', to: 'Parking_B', distance: 4, allowed_modes: ['car'], one_way: false },
    { from: 'Admin_Block', to: 'Hostel_Boys', distance: 3, allowed_modes: ['car', 'bicycle', 'pedestrian'], one_way: false },
    { from: 'SEECS', to: 'SNS', distance: 2.5, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
    { from: 'SMME', to: 'Central_Library', distance: 2, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
    { from: 'Innovation_Center', to: 'Research_Labs', distance: 3, allowed_modes: ['car', 'bicycle'], one_way: false },
    { from: 'Sports_Complex', to: 'Ground', distance: 3, allowed_modes: ['bicycle', 'pedestrian'], one_way: false },
    { from: 'Main_Gate', to: 'SEECS', distance: 3, allowed_modes: ['car'], one_way: true },
  ],
};

// Default export
export const graphData = cityGraphData;

// Map registry
export const MAPS = {
  simple: simpleGraphData,
  city: cityGraphData,
  nust: nustCampusData,
};
